name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: node --version
      - run: npm --version
      - name: npm install and build
        run: |
          npm ci
          npm run build
  deploy-to-docker:
    runs-on: ubuntu-latest
    needs:
      - build
    env:
      DOCKER_USERNAME: "${{ secrets.docker_hub_username }}"
      DOCKER_PASSWORD: "${{ secrets.docker_hub_password }}"
    steps:
      - uses: actions/checkout@v2
      - run: |
         echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
         docker build -t gitlab-search .
         docker tag gitlab-search "${DOCKER_USERNAME}/gitlab-search:${{ github.sha }}"
         docker tag gitlab-search "${DOCKER_USERNAME}/gitlab-search:latest"
         docker push "${DOCKER_USERNAME}/gitlab-search:${{ github.sha }}"
         docker push "${DOCKER_USERNAME}/gitlab-search:latest"
